// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnoDatabase.Migrations
{
    public partial class m2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<double>(
                name: "WeightFactor",
                table: "Services",
                type: "double precision",
                nullable: false,
                defaultValue: 1.0);

            migrationBuilder.CreateIndex(
                name: "IX_SubmittedFlags_FlagServiceId_AttackerTeamId_RoundId",
                table: "SubmittedFlags",
                columns: new[] { "FlagServiceId", "AttackerTeamId", "RoundId" });

            migrationBuilder.CreateIndex(
                name: "IX_SubmittedFlags_FlagServiceId_FlagOwnerId_RoundId_FlagRoundO~",
                table: "SubmittedFlags",
                columns: new[] { "FlagServiceId", "FlagOwnerId", "RoundId", "FlagRoundOffset" });

            migrationBuilder.CreateIndex(
                name: "IX_RoundTeamServiceStatus_ServiceId_GameRoundId_Status",
                table: "RoundTeamServiceStatus",
                columns: new[] { "ServiceId", "GameRoundId", "Status" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_SubmittedFlags_FlagServiceId_AttackerTeamId_RoundId",
                table: "SubmittedFlags");

            migrationBuilder.DropIndex(
                name: "IX_SubmittedFlags_FlagServiceId_FlagOwnerId_RoundId_FlagRoundO~",
                table: "SubmittedFlags");

            migrationBuilder.DropIndex(
                name: "IX_RoundTeamServiceStatus_ServiceId_GameRoundId_Status",
                table: "RoundTeamServiceStatus");

            migrationBuilder.DropColumn(
                name: "WeightFactor",
                table: "Services");
        }
    }
}
